version: "3.7"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    network_mode: "host"
  api:
    image: ${NCP_CONTAINER_REGISTRY}/whatnow-api:0.0.3-8
    container_name: api
    env_file:
      - .env
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
#  location:
#    image: ${{secrets.NCP_CONTAINER_REGISTRY}}/whatnow-location:latest
#    container_name: location
#    network_mode: "host"
#    environment:
#      - TZ=Asia/Seoul
